# Generated by Django 2.2.7 on 2019-11-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),

                ('sFrequency', models.CharField(max_length=32)),
                ('soundType', models.CharField(max_length=32)),
                ('fileType', models.CharField(max_length=32)),
                ('cvtOperation', models.CharField(max_length=32)),
                ('startTime', models.CharField(max_length=32)),
                ('endTime', models.CharField(max_length=32)),


                ('in_bitRate',models.CharField(max_length=128)),
                ('in_sFrequency',models.CharField(max_length=128)),
                ('in_bitPerSample',models.CharField(max_length=128)),
                ('in_length',models.CharField(max_length=128)),
                ('in_cre',models.CharField(max_length=128)),
                ('in_soundType',models.CharField(max_length=128)),
            ],
        ),
    ]
