# Generated by Django 3.1.1 on 2020-09-15 05:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='selectedFile',
            field=models.FileField(blank=True, null=True, upload_to=api.models.upload_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='cvtOperation',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='endTime',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='fileType',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='sFrequency',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='soundType',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='book',
            name='startTime',
            field=models.CharField(max_length=128),
        ),
    ]
